### ISSUE TITLE
Hi Fred!

### ISSUE THREAD

**Issue by pdgonzalez872** [fredwu/datamappify#32]
This isn't an issue. I just wanted to reach out to you and ask you a couple of questions regarding your [blog post](http://fredwu.me/post/147855522498/i-accidentally-some-machine-learning-my-story-of). Awesome post by the way.

I'm a new engineer and have been hearing a lot of the pain points with ActiveRecord you mention in your blog post at work. I haven't had enough experience yet to have the issues you have. Some of the engineers here even mentioned creating something like you have done in this repo, where you implemented the Repository pattern. 

I have a couple of questions for you, if you don't mind:

1 - Did this project help you at work?
2 - Did you use this project in production/professionally?
3 - How was it creating a gem and having to maintain it?
4 - What were your takeaways from this project?

Thank you so much @fredwu!

**Comment by fredwu** [comment]
Hi @pdgonzalez872,

Indeed most seem to have a love and hate relationship when it comes to ActiveRecord. :) To answer your questions:
1. In the beginning yes, as a matter of fact it was actually built specifically for a work project. Later on however, as I mentioned in the README, Datamappify became a bottleneck for us in terms of features and bug fixes as I was the only one with sufficient domain knowledge of how the project was put together, we had to pull it out and revert back to using ActiveRecord.
2. Answered above.
3. Pretty straightforward in this regard, though I had already published a few gems prior to that. If you think about it, packaging your code as a gem is just a form of organising your code and your dependencies, nothing too magical. :)
4. Solving this issue (what is mentioned in the README) is very difficult, partially due to how complex the problem is, and partially due to the overwhelming popularity of ActiveRecord. For instance, [Hanami Model](https://github.com/hanami/model) has seen some slowdowns in its development activities too as there aren't enough people contributing to it. Same observation can be made on [ROM](https://github.com/rom-rb/rom) too - there are usually only a handful of regular contributors... It's going to be a long "battle", perhaps given enough time we'll eventually get there. :)
